### ISSUE TITLE
Is it possible to use interacted FE?

### ISSUE THREAD

**Issue by ezgikurt** [evanjflack/bacon#76]
Hi, great package! I'm just trying to learn Goodman-Bacon decomposition, so sorry if this is not a real "issue". Is it possible to do the decomposition with an interactive FE (like state by year, i.e a model where we have municipality FE + state-by-year FE)? I guess my question both relates to the package but also, would this be possible theoretically? (control groups have the additional requirement of coming from inside the same state, I don't know if this would affect how the weights are calculated)

(I've looked just a tiny bit into the functions and it does not seem to be the case, but maybe there's a valid reason for it so wanted to check. Otherwise I'd be interested to work on it)

**Comment by EdJeeOnGitHub** [comment]
Hi,

Sorry for the delay - I'm not entirely sure.

I don't think as of right now the package can implement this. Whether this is possible theoretically is another question.

My guess is the additional restriction of comparing within groups will create another weighting matrix within state that will also have to be aggregated over to produce the traditional Diff-in-Diff estimate. Maybe this is easy to do; I haven't looked at the paper/literature since we wrote the package I'm afraid.

**Comment by ezgikurt** [comment]
Hi, super late reply. Thanks a lot for the response! I attended a talk of Andrew Goodman-Bacon and asked this briefly, and looking a bit more into how the estimates are calculated this seems very plausible. I am trying it out - should I do a pull request if it works?

**Comment by EdJeeOnGitHub** [comment]
Sounds great!

Pull requests are always welcome :)
